# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CWT_rcpp <- function(t, scales, variance = 1L, threads = 1L) {
    .Call('_CWT_CWT_rcpp', PACKAGE = 'CWT', t, scales, variance, threads)
}

